source 'https://supermarket.chef.io'

cookbook 'base', path: 'site-cookbooks/base'
cookbook 'git', path: 'site-cookbooks/git'
cookbook 'homebrew'
cookbook 'nodenv', path: 'site-cookbooks/nodenv'
cookbook 'osx', path: 'site-cookbooks/osx'
cookbook 'osx-apps', path: 'site-cookbooks/osx-apps'
cookbook 'osx-settings', path: 'site-cookbooks/osx-settings'
cookbook 'postgresql', path: 'site-cookbooks/postgresql'
cookbook 'powerline', path: 'site-cookbooks/powerline'
cookbook 'pyenv', path: 'site-cookbooks/pyenv'
cookbook 'python', path: 'site-cookbooks/python'
cookbook 'rbenv', path: 'site-cookbooks/rbenv'
cookbook 'ruby', path: 'site-cookbooks/ruby'
cookbook 'shell-settings', path: 'site-cookbooks/shell-settings'
cookbook 'terminal', path: 'site-cookbooks/terminal'
cookbook 'vim', path: 'site-cookbooks/vim'
