source 'https://supermarket.chef.io'

cookbook 'asdf', path: 'site-cookbooks/asdf'
cookbook 'base', path: 'site-cookbooks/base'
cookbook 'bash-it', path: 'site-cookbooks/bash-it'
cookbook 'git', path: 'site-cookbooks/git'
cookbook 'go', path: 'site-cookbooks/go'
cookbook 'goenv', path: 'site-cookbooks/goenv'
cookbook 'homebrew'
cookbook 'monaspace', path: 'site-cookbooks/monaspace'
cookbook 'nodenv', path: 'site-cookbooks/nodenv'
cookbook 'oh-my-zsh', path: 'site-cookbooks/oh-my-zsh'
cookbook 'osx', path: 'site-cookbooks/osx'
cookbook 'osx-apps', path: 'site-cookbooks/osx-apps'
cookbook 'osx-settings', path: 'site-cookbooks/osx-settings'
cookbook 'postgresql', path: 'site-cookbooks/postgresql'
cookbook 'powerlevel10k', path: 'site-cookbooks/powerlevel10k'
cookbook 'powerline', path: 'site-cookbooks/powerline'
cookbook 'pyenv', path: 'site-cookbooks/pyenv'
cookbook 'python', path: 'site-cookbooks/python'
cookbook 'rbenv', path: 'site-cookbooks/rbenv'
cookbook 'ruby', path: 'site-cookbooks/ruby'
cookbook 'rust', path: 'site-cookbooks/rust'
cookbook 'shell-settings', path: 'site-cookbooks/shell-settings'
cookbook 'ssh'
cookbook 'ssh-settings', path: 'site-cookbooks/ssh-settings'
cookbook 'sublime-text', path: 'site-cookbooks/sublime-text'
cookbook 'terminal', path: 'site-cookbooks/terminal'
cookbook 'vim', path: 'site-cookbooks/vim'
