#!/bin/bash -e

PLAYBOOK="${1:-playbooks/workstation.yml}"

main() {
  load_venv
  run_playbook
}

load_venv() {
  VENV_DIR=".venv"

  if [ ! -d "$VENV_DIR" ]; then
    install_venv
  fi

  source "$VENV_DIR/bin/activate"
}

install_venv() {
  load_bootstrap_venv
  pip install uv
  uv sync
}

load_bootstrap_venv() {
  BOOTSTRAP_VENV_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/workstation/venv"

  if [ ! -d "$BOOTSTRAP_VENV_DIR" ]; then
    install_bootstrap_venv
  fi

  source "$BOOTSTRAP_VENV_DIR/bin/activate"
}

install_bootstrap_venv() {
  if command -v python3 >/dev/null 2>&1; then
    PYTHON=python3
  elif command -v python >/dev/null 2>&1; then
    PYTHON=python
  else
    echo "No python interpreter found" >&2
    exit 1
  fi

  mkdir -p "$(dirname "$BOOTSTRAP_VENV_DIR")"

  $PYTHON -m venv "$BOOTSTRAP_VENV_DIR"
  source "$BOOTSTRAP_VENV_DIR/bin/activate"
  pip install --upgrade pip
}

run_playbook() {
  PYTHONUNBUFFERED=1 ansible-playbook -c local -i localhost, --ask-become-pass "$PLAYBOOK"
}

main
