- name: Dotfiles
  hosts: localhost

  vars:
    repos:
      - elliterate/dotfiles
      - elliterate/vim-config

  handlers:
    - name: Install repositories
      command: "{{ lookup('env', 'HOME') }}/src/github.com/{{ item }}/install.sh"
      loop: "{{ repos }}"

  tasks:
    - name: Checkout repositories
      git:
        repo: "https://github.com/{{ item }}.git"
        dest: "{{ lookup('env', 'HOME') }}/src/github.com/{{ item }}"
      loop: "{{ repos }}"
      notify: Install repositories
