- name: macOS
  hosts: localhost

  vars:
    formulae:
      - ack
      - ansible
      - asdf
      - awk
      - aws-vault
      - awscli
      - btop
      - curl
      - gh
      - git
      - git-delta
      - gnu-sed
      - gpg
      - htop
      - jq
      - minikube
      - nodenv
      - pstree
      - pyenv
      - qrencode
      - rbenv
      - ruby-build
      - tfenv
      - tree
      - watch
      - wget
      - yq
    casks:
      - 1password-cli
      - brave-browser
      - chromium
      - docker-desktop
      - elgato-control-center
      - elgato-stream-deck
      - firefox
      - github
      - google-chrome
      - google-cloud-sdk
      - hazeover
      - iterm2
      - jetbrains-toolbox
      - lolgato
      - macvim
      - ngrok
      - obsidian
      - scroll-reverser
      - tidal
      - vagrant
      - virtualbox
      - visual-studio-code

  tasks:
    - block:
        - name: Enable Touch ID PAM module
          become: true
          lineinfile:
            path: /etc/pam.d/sudo
            line: "auth       sufficient     pam_tid.so"
            insertbefore: "required"
            firstmatch: true

        - name: Install Homebrew
          shell: |
            curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | bash -
          args:
            creates: /opt/homebrew/bin/brew

        - name: Update Homebrew
          command: /opt/homebrew/bin/brew update

        - name: Install Homebrew formulae
          community.general.homebrew:
            name: "{{ item }}"
            force_formula: true
          loop: "{{ formulae }}"

        - name: Install Homebrew cask
          community.general.homebrew_cask:
            name: "{{ item }}"
          loop: "{{ casks }}"

        - name: Enable locate launch daemon
          become: true
          command: launchctl load -w /System/Library/LaunchDaemons/com.apple.locate.plist

      when: ansible_facts['os_family'] == "Darwin"

- name: macOS Defaults
  import_playbook: macos-defaults.yml
