- name: macOS
  hosts: localhost

  tasks:
    - block:
        - name: Enable Touch ID PAM module
          become: true
          lineinfile:
            path: /etc/pam.d/sudo
            line: "auth       sufficient     pam_tid.so"
            insertbefore: "required"
            firstmatch: true

        - name: Enable locate launch daemon
          become: true
          command: launchctl load -w /System/Library/LaunchDaemons/com.apple.locate.plist

        - name: Disable macOS Tips launch agent
          become: true
          command: launchctl disable system/com.apple.tipsd

      when: ansible_facts['os_family'] == "Darwin"

- name: macOS Packages
  import_playbook: macos-packages.yml

- name: macOS Defaults
  import_playbook: macos-defaults.yml
