- name: macOS
  import_playbook: macos.yml

- name: Dotfiles
  import_playbook: dotfiles.yml

- name: Configure SSH
  import_playbook: ssh-config.yml

- name: Nerd Fonts
  import_playbook: nerd-fonts.yml
