include_recipe 'osx-settings::set_key_repeat_preferences'
include_recipe 'osx-settings::inputrc'
include_recipe 'osx-settings::keyboard'
include_recipe 'osx-settings::locate'
include_recipe 'osx-settings::set_menubar_clock_format'
